cat > pyproject.toml << 'EOF'
[project]
name = "ats-backend"
version = "0.1.0"
description = "ATS Cover Letter Backend"
requires-python = ">=3.10"
dependencies = [
  "fastapi==0.111.0",
  "uvicorn[standard]==0.30.0",
  "pydantic==2.7.1",
  "python-multipart==0.0.9"
]
EOF
